export const UI_TEXT = {
  gameTitle: 'CLICKER GAME',
  tapButton: 'TAP',
  tapHint: 'Tap to earn coins',
  storeTitle: 'GENERATORS',
  boostsTitle: 'MILESTONE BOOSTS',
  settingsTitle: 'SETTINGS',
  tabs: ['STORE', 'TAP', 'BOOSTS'],
  sound: 'SOUND',
  soundDescription: 'Sound effects for purchases',
  vibration: 'VIBRATION',
  vibrationDescription: 'Light feedback for purchases',
  on: 'ON',
  off: 'OFF',
  welcomeBack: 'WELCOME BACK',
  offlineEarnings: 'OFFLINE EARNINGS',
  continue: 'CONTINUE',
  start: 'Click to start',
  buy: 'BUY',
  owned: 'OWNED',
  locked: 'LOCKED',
  unlockHint: 'Keep progressing to unlock',
  milestoneReached: '★ GENERATOR x2',
};